import { mkdirSync, writeFileSync } from "node:fs";
import { render } from "react-email";
import { MagicLinkEmail } from "../emails/magic-link";

/**
 * Pre-renders the React Email template to static HTML once, at build/dev
 * time (via `npm run build:template`, run automatically before `dev`/
 * `deploy`) — never inside the deployed Worker. See emails/magic-link.tsx
 * for why. The token is rendered as a distinctive placeholder here and
 * substituted with the real OTP via a plain string replace at request
 * time in src/index.ts.
 */
const TOKEN_PLACEHOLDER = "__OTP_TOKEN_PLACEHOLDER__";

async function main(): Promise<void> {
  const html = await render(MagicLinkEmail({ token: TOKEN_PLACEHOLDER }));

  mkdirSync(new URL("../src/generated", import.meta.url), { recursive: true });
  writeFileSync(
    new URL("../src/generated/magic-link-html.ts", import.meta.url),
    "// Auto-generated by scripts/build-template.ts — do not edit directly.\n" +
      "// Edit emails/magic-link.tsx and re-run `npm run build:template` instead.\n" +
      `export const MAGIC_LINK_HTML = ${JSON.stringify(html)};\n` +
      `export const TOKEN_PLACEHOLDER = ${JSON.stringify(TOKEN_PLACEHOLDER)};\n`,
  );

  console.log("Wrote src/generated/magic-link-html.ts");
}

main().catch((err: unknown) => {
  console.error(err);
  process.exit(1);
});
